
--DROP [Plt_Image_0138]
USE [master]
ALTER DATABASE [Plt_Image_0138] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [Plt_Image_0138];


--DROP [Plt_Image_0139]
USE [master]
ALTER DATABASE [Plt_Image_0139] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [Plt_Image_0139];


--DROP [Plt_InvoiceImage_0008]
USE [master]
ALTER DATABASE [Plt_InvoiceImage_0008] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [Plt_InvoiceImage_0008];

-----------------------------------------



USE [master]
ALTER DATABASE [PLT_AI] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [PLT_AI] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\PLT_AI\FULL\PLT_AI_20240629_180001.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_AI_Data' TO N'D:\DATA\PLT_AI_Data.mdf',  
MOVE N'Plt_AI_Log' TO N'L:\LOGS\Plt_AI_Log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [PLT_AI] SET MULTI_USER

GO

USE [master]
ALTER DATABASE [Plt_AI_Audit] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_AI_Audit] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_AI_Audit\FULL\Plt_AI_Audit_20240629_180001.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_AI_Audit' TO N'E:\DATA\Plt_Audit.mdf',  
MOVE N'Plt_AI_Audit_log' TO N'L:\LOGS\Plt_AI_Audit_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_AI_Audit] SET MULTI_USER

GO

USE [master]
ALTER DATABASE [Plt_Export] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_Export] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_Export\FULL\Plt_Export_20240629_184454.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_Export_Data' TO N'D:\DATA\Plt_Export_Data.mdf',  
MOVE N'Plt_Export_log' TO N'L:\LOGS\Plt_Export_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_Export] SET MULTI_USER

GO

USE [master]
ALTER DATABASE [PLT_Message] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [PLT_Message] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\PLT_Message\FULL\PLT_Message_20240629_180001.BAK' 
WITH  FILE = 1,  
MOVE N'PLT_Message' TO N'E:\DATA\PLT_Message.mdf',  
MOVE N'PLT_Message_log' TO N'L:\LOGS\PLT_Message_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [PLT_Message] SET MULTI_USER

GO

USE [master]
ALTER DATABASE [COR_DB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [COR_DB] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\COR_DB\FULL\COR_DB_20240629_184454.BAK' 
WITH  FILE = 1,  
MOVE N'COR_DB' TO N'F:\DATA\COR_DB1.mdf',  
MOVE N'COR_DB_log' TO N'L:\LOGS\COR_DB_log1.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [COR_DB] SET MULTI_USER

GO


USE [master]
ALTER DATABASE [ECOL_D365Integration] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [ECOL_D365Integration] 
FROM DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\ECOL_D365Integration\FULL\ECOL_D365Integration_20240629_184454.BAK' 
WITH  FILE = 1,  
MOVE N'ECOL_D365Integration' TO N'F:\DATA\ECOL_D365Integration.mdf',  
MOVE N'ECOL_D365Integration_log' TO N'L:\LOGS\ECOL_D365Integration_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [ECOL_D365Integration] SET MULTI_USER

GO

USE [master]
ALTER DATABASE [Plt_Image] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_Image] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_Image\FULL\Plt_Image_20240629_180001.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_Image_Data' TO N'I:\DATA\Plt_Image.mdf',  
MOVE N'Plt_Image_Log' TO N'L:\LOGS\Plt_Image_Launch_1.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_Image] SET MULTI_USER

GO


USE [master]
ALTER DATABASE [Plt_Image_0141] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_Image_0141] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_Image_0141\FULL\Plt_Image_0141_20240629_200714.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_Image_0141' TO N'I:\DATA\Plt_Image_0141.mdf',  
MOVE N'Plt_Image_0141_log' TO N'L:\LOGS\Plt_Image_0141_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_Image_0141] SET MULTI_USER

GO


USE [master]
ALTER DATABASE [Plt_Image_0142] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_Image_0142] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_Image_0142\FULL\Plt_Image_0142_20240629_200714.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_Image_0142' TO N'I:\DATA\Plt_Image_0142.mdf',  
MOVE N'Plt_Image_0142_log' TO N'L:\LOGS\Plt_Image_0142_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_Image_0142] SET MULTI_USER

GO


USE [master]
ALTER DATABASE [Plt_InvoiceImage_0009] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_InvoiceImage_0009] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_InvoiceImage_0009\FULL\Plt_InvoiceImage_0009_20240629_190138.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_InvoiceImage_0009_Data' TO N'I:\DATA\Plt_InvoiceImage_0009_Data.mdf',  
MOVE N'Plt_InvoiceImage_0009_log' TO N'L:\LOGS\Plt_InvoiceImage_0009_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_InvoiceImage_0009] SET MULTI_USER

GO
USE [master]
ALTER DATABASE [Plt_InvoiceImage_0010] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [Plt_InvoiceImage_0010] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\Plt_InvoiceImage_0010\FULL\Plt_InvoiceImage_0010_20240629_185411.BAK' 
WITH  FILE = 1,  
MOVE N'Plt_InvoiceImage_0010_Data' TO N'I:\DATA\Plt_InvoiceImage_0010_Data.mdf',  
MOVE N'Plt_InvoiceImage_0010_log' TO N'L:\LOGS\Plt_InvoiceImage_0010_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [Plt_InvoiceImage_0010] SET MULTI_USER

GO


---------------------------------------------------------------------------------
USE [Plt_Image]
GO

ALTER VIEW [dbo].[ScanXDatabase]
AS
SELECT image_id, scan_database = 'Plt_image_0142', scan_server = @@SERVERNAME FROM Plt_image_0142..ScanImage
UNION
SELECT image_id, scan_database = 'Plt_image_0141', scan_server = @@SERVERNAME FROM Plt_image_0141..ScanImage
;

ALTER VIEW [dbo].[ScanImage]
AS
SELECT image_id, image_blob FROM Plt_Image_0142..ScanImage
UNION ALL
SELECT image_id, image_blob FROM Plt_Image_0141..ScanImage
;

ALTER VIEW [dbo].[InvoiceImage]
AS
SELECT * FROM Plt_InvoiceImage_0010..InvoiceImage
UNION ALL
SELECT * FROM Plt_InvoiceImage_0009..InvoiceImage
;

ALTER VIEW [dbo].[InvoiceImageXDatabase]
AS
SELECT image_id, image_type, image_database = 'Plt_InvoiceImage_0010', image_server = @@SERVERNAME FROM Plt_InvoiceImage_0010..InvoiceImage
UNION
SELECT image_id, image_type, image_database = 'Plt_InvoiceImage_0009', image_server = @@SERVERNAME FROM Plt_InvoiceImage_0009..InvoiceImage
;
