
--Restore on MI001EQAISQLTEST Server

USE [master]
ALTER DATABASE [PLT_AI] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [PLT_AI] FROM  DISK = N'E:\DATA\PLT_AI_04132023.bak' 
WITH  FILE = 1,  
MOVE N'PLT_AI_Data' TO N'D:\DATA\PLT_AI_Data.mdf',  
MOVE N'PLT_AI_log' TO N'L:\LOGS\PLT_AI_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [PLT_AI] SET MULTI_USER

GO



USE [master]
ALTER DATABASE [ECOL_D365Integration] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [ECOL_D365Integration] FROM  DISK = N'E:\DATA\ECOL_D365Integration_04132023.bak' 
WITH  FILE = 1,  
MOVE N'ECOL_D365Integration' TO N'F:\DATA\ECOL_D365Integration.mdf',  
MOVE N'ECOL_D365Integration_log' TO N'L:\LOGS\ECOL_D365Integration_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [ECOL_D365Integration] SET MULTI_USER

GO


--Restoring from NAS directly
USE [master]
ALTER DATABASE [ECOL_D365Integration] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [PLT_AI] 
FROM  DISK = N'\\10.2.76.101\MI001SQL01\MI001EQAISQLC01$PRDEQAISQLAG\PLT_AI\FULL\PLT_AI_20240629_180001.BAK' 
WITH  FILE = 1,  
MOVE N'PLT_AI' TO N'F:\DATA\PLT_AI.mdf',  
MOVE N'PLT_AI_log' TO N'L:\LOGS\PLT_AI_log.ldf',  
NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [PLT_AI] SET MULTI_USER

GO

